# Generated by Django 5.2.7 on 2025-12-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_category_id_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'permissions': [('can_edit_others_posts', 'Can edit others posts')]},
        ),
    ]
